JuliaFlorea.Web/Controllers/DepotInventoryController.cs
using JuliaFlorea.DataModel;
using JuliaFlorea.Domain;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Web.Mvc;

namespace JuliaFlorea.Web.Controllers
{
    public class DepotInventoryController : Controller
    {
        private readonly AppDbContext _dbContext;
        private readonly DepotInventoryService _depotInventoryService;

        public DepotInventoryController(AppDbContext dbContext, DepotInventoryService depotInventoryService)
        {
            _dbContext = dbContext;
            _depotInventoryService = depotInventoryService;
        }

        public DepotInventoryController()
        {
        }

        public ActionResult Index()
        {
            var depotInventory = _dbContext.DrugUnits.Include(du => du.DrugType).Include(du => du.Depot).ToList();
            ViewBag.Depots = _dbContext.Depots.ToList();
            ViewBag.DrugUnits = depotInventory;
            return View(depotInventory);
        }

        [HttpPost]
        public ActionResult Associate(string associateDepotId, int associateStartPickNumber, int associateEndPickNumber)
        {
            var drugUnits = _dbContext.DrugUnits.ToList();
            var selectedDepot = _dbContext.Depots.FirstOrDefault(d => d.DepotId == associateDepotId);

            if (selectedDepot == null)
            {
                ModelState.AddModelError("", "Selected depot does not exist.");
                ViewBag.Depots = _dbContext.Depots.ToList();
                var depotInventory = _dbContext.DrugUnits.Include(du => du.DrugType).Include(du => du.Depot).ToList();
                return View("Index", depotInventory);
            }

            _depotInventoryService.AssociateDrugs(ref drugUnits, selectedDepot.DepotId, associateStartPickNumber, associateEndPickNumber);
            ViewBag.DrugUnits = drugUnits;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Disassociate(int disassociateStartPickNumber, int disassociateEndPickNumber)
        {
            var drugUnits = _dbContext.DrugUnits.ToList();
            _depotInventoryService.DisassociateDrugs(ref drugUnits, disassociateStartPickNumber, disassociateEndPickNumber);

            ViewBag.DrugUnits = drugUnits;

            return RedirectToAction("Index");
        }
    }
}

JuliaFlorea.Web/Views/DepotInventory/Index.cshtml
@{
    ViewData["Title"] = "Depot Inventory";
    var headerCellStyle = "border: 1px solid #836096; border-color: #836096; padding: 8px; text-align: center;";
    var cellStyle = "border: 1px solid #836096; border-color: #836096; padding: 8px; text-align: center; vertical-align: middle;";
    var titleStyle = "text-align: center;";
}

<h2 style="@titleStyle">Depot Inventory</h2>

<div class="row">
    <div class="col-md-6">

        <h3>Associate Drugs</h3>
        @using (Html.BeginForm("Associate", "DepotInventory", FormMethod.Post))
        {
            <div class="form-group">
                @Html.Label("Depot:")
                @Html.DropDownList("associateDepotId", new SelectList(ViewBag.Depots, "DepotId", "DepotName"), "Select a Depot", new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.Label("Start Pick Number:")
                @Html.TextBox("associateStartPickNumber", null, new { @class = "form-control", type = "number" })
            </div>
            <div class="form-group">
                @Html.Label("End Pick Number:")
                @Html.TextBox("associateEndPickNumber", null, new { @class = "form-control", type = "number" })
            </div>
            <button type="submit" class="btn btn-primary">Associate</button>
        }
    </div>

    <div class="col-md-6">
        <h3>Disassociate Drugs</h3>
        @using (Html.BeginForm("Disassociate", "DepotInventory", FormMethod.Post))
        {
            <div class="form-group">
                @Html.Label("Start Pick Number:")
                @Html.TextBox("disassociateStartPickNumber", null, new { @class = "form-control", type = "number" })
            </div>
            <div class="form-group">
                @Html.Label("End Pick Number:")
                @Html.TextBox("disassociateEndPickNumber", null, new { @class = "form-control", type = "number" })
            </div>
            <button type="submit" class="btn btn-danger">Disassociate</button>
        }
    </div>
</div>

@if (ViewBag.DrugUnits != null)
{
    <h3>Drug Units</h3>
    <table class="table">
        <thead>
            <tr>
                <th style="@headerCellStyle">ID</th>
                <th style="@headerCellStyle">Pick Number</th>
                <th style="@headerCellStyle">Depot Name</th>
                <th style="@headerCellStyle">Drug Type Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var drugUnit in ViewBag.DrugUnits)
            {
                <tr>
                    <td style="@cellStyle">@drugUnit.DrugUnitId</td>
                    <td style="@cellStyle">@drugUnit.PickNumber</td>
                    <td style="@cellStyle">@(drugUnit.Depot != null ? drugUnit.Depot.DepotName : "Not Associated")</td>
                    <td style="@cellStyle">@(drugUnit.DrugType != null ? drugUnit.DrugType.DrugTypeName : "Unknown Type")</td>
                </tr>
            }
        </tbody>
    </table>
}