JuliaFlorea.Web/Controllers/SiteController.cs
using JuliaFlorea.DataModel;
using JuliaFlorea.Domain;
using JuliaFlorea.Domain.DbService;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace JuliaFlorea.Web.Controllers
{
    public class SiteController : Controller
    {
        private readonly AppDbContext _dbContext;
        private readonly SiteInventoryDbHandler _siteInventoryDbHandler;
       

        public SiteController(AppDbContext dbContext, SiteInventoryDbHandler siteInventoryDbHandler)
        {
            _dbContext = dbContext;
            _siteInventoryDbHandler = siteInventoryDbHandler;
           
        }



        // GET: Depot
        public ActionResult Index()
        {
            var siteWithCountry = _dbContext.Sites.Include(s => s.Country).ToList();
            return View(siteWithCountry);
        }

        // GET: Depot/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Site site = _dbContext.Sites.Include(s => s.Country).SingleOrDefault(s => s.SiteId == id);
            ;

            if (site == null)
            {
                return HttpNotFound();
            }

            return View(site);
        }

        // GET: Depot/Create
        public ActionResult Create()
        {
            ViewBag.CountryList = new SelectList(_dbContext.Countries, "CountryId", "CountryName");

            return View();
        }

        // POST: Depot/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SiteName,CountryCode")] Site site)
        {
            if (ModelState.IsValid)
            {

                _dbContext.Add(site);
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CountryList = new SelectList(_dbContext.Countries, "CountryId", "CountryName", site.CountryCode);
            return View(site);
        }

        // GET: Depot/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Site site = _dbContext.Sites.Find(id);
            if (site == null)
            {
                return HttpNotFound();
            }
            ViewBag.CountryList = new SelectList(_dbContext.Countries, "CountryId", "CountryName", site.CountryCode);
            return View(site);
        }

        // POST: Depot/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SiteId,SiteName,CountryCode")] Site site)
        {
            if (ModelState.IsValid)
            {



                _dbContext.Entry(site).State = EntityState.Modified;
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CountryList = new SelectList(_dbContext.Countries, "CountryId", "CountryName", site.CountryCode);

            return View(site);
        }

        // GET: Depot/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Site site = _dbContext.Sites.Include(s => s.Country).SingleOrDefault(s => s.SiteId == id);
            if (site == null)
            {
                return HttpNotFound();
            }
            return View(site);
        }

        // POST: Depot/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Site site = _dbContext.Sites.Find(id);
            _dbContext.Sites.Remove(site);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult RequestDrugs(string siteId)
        {
            if (siteId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Site site = _dbContext.Sites.Find(siteId);
            if (site == null)
            {
                return HttpNotFound();
            }

            ViewBag.DrugTypeList = new SelectList(_dbContext.DrugTypes, "DrugTypeId", "DrugTypeName");

            return View(site);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RequestDrugs(string siteId, string drugCode, int quantity)
        {
            if (string.IsNullOrEmpty(siteId) || string.IsNullOrEmpty(drugCode) || quantity <= 0)
            {
                ModelState.AddModelError("", "Invalid input data.");
                return RedirectToAction("RequestDrugs", new { siteId });
            }

            _siteInventoryDbHandler.UpdateSiteInventory(siteId, drugCode, quantity);

            
            Site updatedSite = _dbContext.Sites
                .Include(s => s.Country.Depot.DrugUnits)
                .FirstOrDefault(s => s.SiteId == siteId);

            ViewBag.DrugTypeList = new SelectList(_dbContext.DrugTypes, "DrugTypeId", "DrugTypeName");
            ViewBag.RequestedDrugUnits = updatedSite?.Country?.Depot?.DrugUnits.Where(du => du.DrugType != null && du.DrugType.DrugTypeId == drugCode).ToList();
            ViewBag.RequestedQuantity = quantity;
            return View(updatedSite);

        }
    }
}

JuliaFlorea.Web/Views/Site/Create.cshtml
@model JuliaFlorea.DataModel.Site

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Site</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.SiteName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SiteName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SiteName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CountryCode, "Country", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CountryCode, ViewBag.CountryList as SelectList, "Select Country", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CountryCode, "", new { @class = "text-danger" })
        </div>
    </div>

    




    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JuliaFlorea.Web/Views/Site/Delete.cshtml
@model JuliaFlorea.DataModel.Site

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Site</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.SiteId)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.SiteId)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.SiteName)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.SiteName)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Country.CountryName)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Country.CountryName)
    </dd>
</dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JuliaFlorea.Web/Views/Site/Details.cshtml
@model JuliaFlorea.DataModel.Site

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Site</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SiteId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SiteId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SiteName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SiteName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Country.CountryName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Country.CountryName)
        </dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SiteId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JuliaFlorea.Web/Views/Site/Edit.cshtml
@model JuliaFlorea.DataModel.Site

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Site</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SiteId)

        <div class="form-group">
            @Html.LabelFor(model => model.SiteName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SiteName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SiteName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryCode, "Country", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CountryCode, ViewBag.CountryList as SelectList, "Select Country", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JuliaFlorea.Web/Views/Site/Index.cshtml


@model IEnumerable<JuliaFlorea.DataModel.Site>

@{
    ViewBag.Title = "Sites";
    var headerCellStyle = "border: 1px solid #836096; border-color: #836096; padding: 8px; text-align: center;";
    var cellStyle = "border: 1px solid #836096; border-color: #836096; padding: 8px; text-align: center; vertical-align: middle;";
    var titleStyle = "text-align: center;";
    var buttonStyle = "background-color: #836096; color: white; border: none; padding: 5px 10px; text-align: center; text-decoration: none; display: inline-block; font-size: 12px; margin: 2px;";
}

<h2 style="@titleStyle">Sites</h2>

<p>
    <a href="@Url.Action("Create")" style="@buttonStyle">Create New</a>
</p>
<table class="table">
    <tr>
        <th style="@headerCellStyle">
            @Html.DisplayNameFor(model => model.SiteId)
        </th>
        <th style="@headerCellStyle">
            @Html.DisplayNameFor(model => model.SiteName)
        </th>

        <td style="@cellStyle">
            @Html.DisplayNameFor(model => model.Country.CountryName)
        </td>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
             <td style="@cellStyle">
                @Html.DisplayFor(modelItem => item.SiteId)
            </td>
            <td style="@cellStyle">
                @Html.DisplayFor(modelItem => item.SiteName)
            </td>
            
            <td style="@cellStyle">
                @Html.DisplayFor(modelItem => item.Country.CountryName)
            </td>

            <td>


                <a href="@Url.Action("Edit", new { id = item.SiteId })" style="@buttonStyle">Edit</a>
                <a href="@Url.Action("Details", new { id = item.SiteId })" style="@buttonStyle">Details</a>
                <a href="@Url.Action("Delete", new { id = item.SiteId })" style="@buttonStyle">Delete</a>
                <a href="@Url.Action("RequestDrugs", new { siteId = item.SiteId })" style="@buttonStyle">Request Drugs</a>
                @*@Html.ActionLink("Request Drugs", "RequestDrugs", new { siteId = item.SiteId })*@
            </td>
        </tr>
    }

</table>

JuliaFlorea.Web/Views/Site/RequestDrugs.cshtml
@model JuliaFlorea.DataModel.Site

@{
    ViewData["Title"] = "Request Drugs";
    var headerCellStyle = "border: 1px solid #836096; border-color: #836096; padding: 8px; text-align: center;";
    var cellStyle = "border: 1px solid #836096; border-color: #836096; padding: 8px; text-align: center; vertical-align: middle;";
    var titleStyle = "text-align: center;";
}

<h2 >Request Drugs for @Model.SiteName</h2>

<div class="row">
    <div class="col-md-6">
        <h3>Request Drugs</h3>
        @using (Html.BeginForm("RequestDrugs", "Site", new { siteId = Model.SiteId }, FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                @Html.Label("Drug Type:")
                @Html.DropDownList("drugCode", (SelectList)ViewBag.DrugTypeList, "Select a Drug Type", new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.Label("Quantity:")
                @Html.TextBox("quantity", null, new { @class = "form-control", type = "number", min = "1" })
            </div>
            <button type="submit" class="btn btn-primary">Request Drugs</button>
        }
    </div>
</div>

@if (ViewBag.RequestedDrugUnits != null && ViewBag.RequestedDrugUnits.Count > 0)
{
    <h3 style="@titleStyle">Requested Drugs Details</h3>
    <table class="table">
        <thead>
            <tr>
                <th style="@headerCellStyle">Drug Unit ID</th>
                <th style="@headerCellStyle">Pick Number</th>
                <th style="@headerCellStyle">Depot Name</th>
                <th style="@headerCellStyle">Drug Type Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var drugUnit in ((List<JuliaFlorea.DataModel.DrugUnit>)ViewBag.RequestedDrugUnits).Take((int)ViewBag.RequestedQuantity))
            {
                <tr>
                    <td style="@cellStyle">@drugUnit.DrugUnitId</td>
                    <td style="@cellStyle">@drugUnit.PickNumber</td>
                    <td style="@cellStyle">@(drugUnit.Depot != null ? drugUnit.Depot.DepotName : "Not Associated")</td>
                    <td style="@cellStyle">@(drugUnit.DrugType != null ? drugUnit.DrugType.DrugTypeName : "Unknown Type")</td>
                </tr>
            }
        </tbody>
    </table>
}